language: python
sudo: false
deploy:
  provider: pypi
  user: abeelen
  password:
    secure: idXuosz+94Q1u/OBrNEdr+2A30ajfLYk5EDWEXH88MNpluKKqXnZ2YtZU7ksu1FmsVvyZqcvMmGbxvwi3vNEiZpwh1nj5RLGNaa/5iRtnBDgVrYg1gvEzdtUfQ+1NOKnbjKprFJdUOK1yshmDGX3DBR1t8j85lbY7HAZjaseA2Hf1sOUvO2XZs+rMmR5K6rge/mGvbd0uNXtK7ofbB6N2hbeCJp6+Qgn+4zyXZ95qvIAoTo/uBOgjFD1SUbH0IySqtLhvhUqqPjs4FF9F9krp/MMx+gbsYbB+lb1bT2N14cFn6phalgO2NmL4D3ccRY6Q5MfvufwY8KAjwGNb4BxoNxYvG5NMzjJtLczg3ItAxAUBrsiPfi8LmxHpLJFTvnJCZxWGH+KqkHdlU+vwm4MFdJrxRVJb++MR4A0lHAgtz/lCiG+iHSrdV0rYiNMmVUgjrs+uI+yTp6Qup+TUf8gsAgCkaQjYqr4Op3AXEKlRGGwadtriRPh8lzOGpMhU71jSaFoNcZ7JHijJuc3D3xqozxFF01OkJg7h0rwoVQfs51dxtRRxvJEXhkCLhdXgAUZNbOpsVP7QFhuMg+xIkpnhX6tKl06M1rp8GGyYtYUew3FOr7/ffC5NnXwAgKJj1aMgNDF77CYFN3fVEw8EyYLWDcfFVYF72Vq5xrxrBxoqmg=
  on:
    tags: true
    repo: abeelen/nikamap
env:
  matrix:
    - ASTROPY_VERSION=2.0.4
    - ASTROPY_VERSION=3.0
  global:
  - PIP_DEPS="pytest coveralls pytest-cov flake8 pytest-mpl matplotlib"

python:
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  exclude:
  - python: "3.4"
    env: ASTROPY_VERSION=3.0

install:
  - travis_retry pip install $PIP_DEPS
  - travis_retry pip install -q astropy==$ASTROPY_VERSION
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install .

script:
  - flake8 --ignore N802,N806,E501,F841,F401 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/`
  -  MPLBACKEND="agg" python setup.py test

after_success:
  - coveralls
