dist: trusty
sudo: required
language: python

deploy:
  provider: pypi
  user: abeelen
  password:
    secure: idXuosz+94Q1u/OBrNEdr+2A30ajfLYk5EDWEXH88MNpluKKqXnZ2YtZU7ksu1FmsVvyZqcvMmGbxvwi3vNEiZpwh1nj5RLGNaa/5iRtnBDgVrYg1gvEzdtUfQ+1NOKnbjKprFJdUOK1yshmDGX3DBR1t8j85lbY7HAZjaseA2Hf1sOUvO2XZs+rMmR5K6rge/mGvbd0uNXtK7ofbB6N2hbeCJp6+Qgn+4zyXZ95qvIAoTo/uBOgjFD1SUbH0IySqtLhvhUqqPjs4FF9F9krp/MMx+gbsYbB+lb1bT2N14cFn6phalgO2NmL4D3ccRY6Q5MfvufwY8KAjwGNb4BxoNxYvG5NMzjJtLczg3ItAxAUBrsiPfi8LmxHpLJFTvnJCZxWGH+KqkHdlU+vwm4MFdJrxRVJb++MR4A0lHAgtz/lCiG+iHSrdV0rYiNMmVUgjrs+uI+yTp6Qup+TUf8gsAgCkaQjYqr4Op3AXEKlRGGwadtriRPh8lzOGpMhU71jSaFoNcZ7JHijJuc3D3xqozxFF01OkJg7h0rwoVQfs51dxtRRxvJEXhkCLhdXgAUZNbOpsVP7QFhuMg+xIkpnhX6tKl06M1rp8GGyYtYUew3FOr7/ffC5NnXwAgKJj1aMgNDF77CYFN3fVEw8EyYLWDcfFVYF72Vq5xrxrBxoqmg=
  on:
    tags: true
    repo: abeelen/nikamap

addons:
  sonarcloud:
    organization: "abeelen-github"
    token:
      secure: "J5jeO/6I3y+4jHbsBP0Lp6Zqfq4plQNcU5spUpVUH+F6EIfOYPfNiiBjSp0H/YUsQlOWSKzM1DobATKjaqjxAEANRqXUMrfh6jwZmIKiXJqePdMqkYxGU3NhgXXRizkXnEuDyKf42OQuBY/OvA8m7/w5S4LWIrjeizpk8yGuNZYL888kE9wquqBdWTYU+6gpwwe6iodWe2avHv0beCpTAC9flRITxK1TwVlrMys+zU6LQ+mE6JGqSQmbtVCPSffSyy+u7UGumJdXRHVUec3My35OFbDG6O1VRnH8JBh1fg+pO80O+YTWO6In2KYZhPFZvKReYKwim2Rmaig0lwSnSNolqNRK8hqj3kHRZvTtpBs1K+EdvCxIBNfEoyAZZOqWG/KNcN0e+eSB8nbSwO7QfSS4ph7pj8jzQ/QvxyVOtPsJ1OYSBtdx8RM4Gx3bvbGmv7VYDpZSre0BbIaDlDieXjGT6XVwLqofZbmFb0atE5pI/lBUup9lr3hmj9ZBf337T2I+OM4+FaV8mPbxkqbnymeZS05K6RS4v4mpclXXEUViLltA4+nDXGBRIcij4AEFvNJ19UAwRsihn4BueNBrKDtLFbOQ1KAtHfWV5kJ6WqVAsjZna9YyQl18Flq0Dpty+ANlgek8r2IVHz5Fxi/uX6e72VdmTrQoCdrW2VuYvWA="


env:
  matrix:
    # - ASTROPY_VERSION=3.0
    - NUMPY_VERSION=1.10.4
    - NUMPY_VERSION=1.14.5
    - NUMPY_VERSION=1.13.3
    - NUMPY_VERSION=1.11.3
    - NUMPY_VERSION=1.12.1

  global:
  - PIP_DEPS="pytest coveralls pytest-cov flake8 pytest-mpl matplotlib"
  - ASTROPY_VERSION=2.0.4

python:
  # - "3.4"
  # - "3.5"
  - "3.6"

matrix:
  exclude:
  - python: "3.4"
    env: ASTROPY_VERSION=3.0

install:
  - travis_retry pip install $PIP_DEPS
  - travis_retry pip install -q numpy==$NUMPY_VERSION
  - travis_retry pip install -q astropy==$ASTROPY_VERSION
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install .

script:
  - flake8 --ignore N802,N806,E501,F841,F401 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/`
  - pip freeze
  - MPLBACKEND="agg" python setup.py test
  - sonar-scanner

after_success:
  - coveralls
