

[tox]
min_version = 4.0
# Matrice factorisée Python x photutils
envlist =
    py310-photutils190
    py310-photutils1130
    py311-photutils1130
    py311-photutils202
    py311-photutils230
    py312-photutils202
    py312-photutils230
    py313-photutils202
    py313-photutils230
    build_docs



[testenv]
deps =
    pytest
    pytest-cov
    pytest-mpl
    pytest-doctestplus
    reproject
    setuptools_scm>=6.2
    powspec>=0.3
    scikit-image
    photutils190: photutils==1.9.0
    photutils1130: photutils==1.13.0
    photutils202: photutils==2.0.2
    photutils230: photutils==2.3.0
    photutils190,photutils1130: numpy>=1.22
    photutils190,photutils1130: scipy>=1.7.0
    photutils190,photutils1130: matplotlib>=3.5.0
    photutils190,photutils1130: astropy>=5.2
    photutils202: numpy>=1.24
    photutils202: scipy>=1.10.0
    photutils202: matplotlib>=3.7.0
    photutils202: astropy>=5.3
    photutils202: scikit-image>=0.19.0
    photutils230: numpy>=1.25
    photutils230: scipy>=1.11.1
    photutils230: matplotlib>=3.8
    photutils230: astropy>=6.0
    photutils230: scikit-image>=0.21
extras = test
set_env =
    MPLBACKEND = agg
change_dir = .tmp/{envname}
commands =
    pytest --pyargs nikamap --cov nikamap --cov-report xml:coverage.xml --cov-report term-missing {posargs}

[testenv:build_docs]
description = invoke sphinx-build to build the HTML docs
change_dir =
    doc
extras =
    docs
commands =
    sphinx-build -j auto --color --keep-going -b html -d _build/.doctrees . _build/html {posargs}
